### ISSUE TITLE
Fix object at specific position?

### ISSUE THREAD

**Issue by WhoAmI1x** [ViroCommunity/viro#106]
I use ViroVideo inside ViroARImageMarker but video is not kept position. If i move camera the video move together. Pls help me!

**Comment by mikevocalz** [comment]
> [WhoAmI1x](/WhoAmI1x)

did you find a fix?

**Comment by donni106** [comment]
@WhoAmI1x any update on this issue?
@ardasnturk an me also have problems with objects moving when moving/turning the smartphone.
