### ISSUE TITLE
@viro-community/react-viro does not contain a valid config plugin

### ISSUE THREAD

**Issue by bethanylu** [ViroCommunity/viro#109]
## Description

I am attempting to add @viro-community/react-viro to my existing Expo project. 

After installing the package using 

$ yarn add @viro-community/react-viro

I added 
`"plugins": [ "@viro-community/react-viro" ]`
to my app.json file  under `"expo":{}`

When I run 
$ expo start 
or 
$ expo prebuild
I get the following error:

> Package "@viro-community/react-viro" does not contain a valid config plugin. Module must export a function from file: .../node_modules/@viro-community/react-viro/index.js

I did not manually link as I have not ejected my Expo project yet...please let me know if I should. I am new to both Expo and Viro React so any help is much appreciated!

## Environment
1. Development OS: Mac
2. Device OS & Version: iOS version 11.1
3. Version: 
react-native-cli: 2.0.1
react-native: 0.64.3
4. Device(s): iPhone 12 Pro Max

**Comment by vecpeng** [comment]
I have the same issue. Is there any way to solve it?

**Comment by vecpeng** [comment]
it seems that support for expo hasn't been published to npm.
Maybe we should wait until next version.

**Comment by Neil-140301** [comment]
same issue. please fix it as soon as possible. I need viro for my project

**Comment by shalin-jasani747** [comment]
@Neil-140301 
`"@viro-community/react-viro": "ViroCommunity/viro"`
Add this line in your package.json and run yarn/npm install command. It will fetch data directly from the git repo and also you get the valid config file

**Comment by Neil-140301** [comment]
ok, I will try this. Thanks

**Comment by robertjcolley** [comment]
@Neil-140301 try using 2.23.0 - I had updated the docs without deploying the release. Also check out the expo-viro-starter-kit we have https://github.com/ViroCommunity/expo-viro-starter-kit if you're having any trouble!
