### ISSUE TITLE
Invariant Violation: Tried to register two views with same name VRTQuad

### ISSUE THREAD

**Issue by Saalim95** [ViroCommunity/viro#117]
## Environment
1. Development OS: MacOS Big Sur
2. Device OS & Version: iOS 14.7 and Android 9
3. Version: "@viro-community/react-viro": "^2.23.0", and "react-native": "0.61.5",
4. Device(s): Redmi Note 8 Pro and iPhone XR

## Description

Getting this error while running thre app after following all the necessary installation instructions for Android and iOS both.
![WhatsApp Image 2022-03-29 at 11 14 34 AM](https://user-images.githubusercontent.com/19245026/160627847-d842fd90-3978-413d-b1ad-5eb9480d911e.jpeg)

**Comment by francois-pasquier** [comment]
For some reason you have to import each component you want to use from viro by its direct path.

e.g: /components/something

That said, this doesn't fix the actual issue.

**Comment by Saalim95** [comment]
Thanks @francois-pasquier . I am no longer facing this issue.

**Comment by tjikaljedy** [comment]
I face some problem 
 "react": "17.0.2",
 "react-native": "0.66.4",

    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "@viro-community/react-viro": "^2.23.0",

**Comment by tjikaljedy** [comment]
Hi All, 

Another workaround downgrade the viro to 2.20.2 , when i tested with react-native 0.65.1 is working

**Comment by scrolls-mckenzie** [comment]
> 

Hello. I am facing this issue too. Have tried to play with versions of dependencies without success. How did you solve this issue

**Comment by tjikaljedy** [comment]
Hi Scrolls,

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/6268790/176389733-b83e2cd8-f217-4707-a6aa-171998016fc7.png">

**Comment by scrolls-mckenzie** [comment]
> Hi Scrolls,
> 
> <img alt="image" width="1033" src="https://user-images.githubusercontent.com/6268790/176389733-b83e2cd8-f217-4707-a6aa-171998016fc7.png">
> 
> under root folder of your apps, need to create react-viro.d.ts (to fix import problem) and react-viro.d.ts as:
> 
> declare module '@viro-community/react-viro';
> 
> Thx

Hi @tjikaljedy 

Thanks for the reply. I had solved the problem by following your post #136 and edited the VRTSurface files and changed it to remove the second instance or VRTQuad being called. That solved the problem for me and I have successfully launched a dev build. 

Great work and thanks very much for being active and responding.
