### ISSUE TITLE
Urgent Help with Expo Integration.

### ISSUE THREAD

**Issue by ktjh123** [ViroCommunity/viro#142]
After following the guide, i got this when i run expo run:android

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer:2.7.1.
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Appreciate any help

**Comment by siabard** [comment]
Update your dependencies in `android/app/build.gradle`

I changed version of `exoplayer` from 2.7.1 to 2.17.1 then it compiled. (But I cannot get camera working)

```
implementation group: 'com.google.android.exoplayer', name: 'exoplayer', version: '2.17.1'
```

**Comment by equationalapplications** [comment]
exoplayer 2.7.1 was in jcenter but is not in maven, so it can no longer be found at build time, it seems. I am trying exoplayer 2.13.3 because it is the lowest version available on maven.

**Comment by skizzo** [comment]
Hi, did you manage to solve this? Trying to get Viro running on React Native 0.71.7.

**Comment by ViktorVojtek** [comment]
@skizzo Have you managed somehow?

**Comment by skizzo** [comment]
@ViktorVojtek I don't use Expo, but I managed to get Viro running on a regular RN 0.71.7 (iOS & Android) project. 

Setting the exoplayer version to `2.17.1` like @siabard suggested was necessary to get it running on Android nonetheless:

> Update your dependencies in `android/app/build.gradle`
> 
> I changed version of `exoplayer` from 2.7.1 to 2.17.1 then it compiled. (But I cannot get camera working)
> 
> ```
> implementation group: 'com.google.android.exoplayer', name: 'exoplayer', version: '2.17.1'
> ```

**Comment by ViktorVojtek** [comment]
@skizzo Thanks a lot! :)
