### ISSUE TITLE
Cloud anchors / scene persistency

### ISSUE THREAD

**Issue by Naphier** [ViroCommunity/viro#15]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Description
I've been looking a bit and not seeing any info on cloud anchors or scene persistency. Is this available in Viro yet? Having anchors be able to reappear in accurate positions (not geo coordinates because GPS is loose) is an extremely powerful feature enabling software to be used to augment a user's real life space without image or object markers.

**Comment by doranteseduardo** [comment]
Hello Naphier,
The Cloud Anchors feature is already integrated in ViroCore, but not in ViroReact.

The team is already working on adding the bridge to ViroReact so the feature can be consumed in there.
For now, it can be used only in ViroCore (native Android projects), if it helps, [the documentation is in here](https://virocore.viromedia.com/docs/ar-cloud).

Best regards!

**Comment by Naphier** [comment]
Awesome. Thanks! 
Is there a timeline? Does it need help? Not sure I could dedicate time but may try if it's not already being worked.

**Comment by doranteseduardo** [comment]
Oh, contribution is always wanted!
Join us on Discord (link is on the README) and we will gladly discuss how you can help.

**Comment by Naphier** [comment]
Thanks, I was blind and could not see that image for the life of me!
I'll see what I can do to help. Closing this.

**Comment by devpascoe** [comment]
Hey folks, just checking in on progress for bridging ARCloud / Cloud Anchors for RN. <3
