### ISSUE TITLE
Convert FBX file to VRX

### ISSUE THREAD

**Issue by DorelisMarcelo** [ViroCommunity/viro#156]
Hi, i need to convert an FBX file to VRX but i cannot make work the script https://github.com/ViroCommunity/ViroFBX .

When i try tu use it i get:./ViroFBX: command not found

**Comment by Shasikhan** [comment]
First of all this conversion command is for mac and linux systems. 
if you are using mac, in terminal, go to your project, then in node_modules -> @viro-community -> react-viro -> bin
Here run conversion command
./ViroFBX path/to/model.fbx path/to/model.vrx

It will work.

**Comment by waqaskhanroghani** [comment]
Its works
Thanks for your help :)

**Comment by DorelisMarcelo** [comment]
Hi! i found out that it works fine with Java JRE 8, so make sure that yout JAVA_HOME enviroment variable is well set and calling JRE 8. Thanks!
