### ISSUE TITLE
After build with EAS, the app does not work in iOS simulator

### ISSUE THREAD

**Issue by ardasnturk** [ViroCommunity/viro#162]
# Requirements: 
  - [x] Review the [documentation](https://viro-community.readme.io/)
  - [x] Search for existing issues in: [viromedia/viro](https://github.com/viromedia/viro/issues) & [ViroCommunity/viro](https://github.com/ViroCommunity/viro/issues)
  - [x] Use the latest [ViroReact release](https://viro-community.readme.io/docs/releases)

## Environment
1. Development OS: Mac
2. Device OS & Version: iOS version (15.5, 16)
3. Version:  `"expo": "^45.0.0"`, `"react": "17.0.2"`, `"react-native": "0.68.2"`, `"@viro-community/react-viro": "^2.23.0"`
4. Device(s): Simulator

## Description
We are building with EAS for the application I am working on. It runs smoothly on real devices. Before I added the Viro package, it was working fine in iOS simulator. Now, as you can see in the video, the application directly crashes without opening. I did a research about this, but I couldn't find a correct answer. Viro's documentation says that it won't work with the simulator. At the moment I can run the application on Android Emulator, I just can't use the features of Viro package. I need to run it on iOS simulator to develop the application faster. 
I am waiting for your help. 
Thank you.

## Reproducible Demo
`Library not loaded: @rpath/GTMSessionFetcher.framework/GTMSessionFetcher`

`Referenced from: /Users/USER/Library/Developer/CoreSimulator/Devices/.../data/Containers/Bundle/Application/.../AppName/Frameworks/ViroKit.framework/ViroKit`

`Reason: tried: ‘/Users/username/Library/Developer/CoreSimulator/Devices/.../data/Containers/Bundle/Application/.../AppName/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher’ (no such file), `

`‘/Users/username/Library/Developer/CoreSimulator/Devices/.../data/Containers/Bundle/Application/.../AppName/Frameworks/ViroKit.framework/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher’ (no such file), `

`’/Users/username/Library/Developer/CoreSimulator/Devices/.../data/Containers/Bundle/Application/...,`

https://user-images.githubusercontent.com/11755668/191977857-f18b9ad7-3053-476f-a441-09495f8721ca.mp4

**Comment by billvog** [comment]
For anybody stuck on this, using a later version (`2.40.0` for example), I've been struggling with that for some time (not being able to run the app on the iOS simulator) and I fixed it by downgrading to `^2.30.0`. It works fine, both on the simulator and the physical device.
