### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by danyhiol** [ViroCommunity/viro#17]
Is there any future plan to add typescript support?

**Comment by bilewinters** [comment]
There is! It's on our todo list, and we have done some experimenting with partial transitions.

**Comment by bilewinters** [comment]
https://github.com/ViroCommunity/viro/projects/1#card-55374105

**Comment by danyhiol** [comment]
Oh! That's fantastic and would be a source of documentation.

**Comment by qu4sar** [comment]
Try here -> https://github.com/intractive-app/react-viro-to-dts 
;)

**Comment by robertjcolley** [comment]
This is landing soon! #72 was merged in today
