### ISSUE TITLE
ViroVideo does not work on iOS

### ISSUE THREAD

**Issue by marcofugaro** [ViroCommunity/viro#18]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: **Mac**
2. Device OS & Version: **iOS version 13.6.1**
3. Version: **ViroReact 2.20.2,  React Native 0.64.0**
4. Device(s): **iPhone XS**

## Description
While attempting to use any video on iOS, this error pops up. I don't know what is causing it.

```
unrecognized selector sent to instance
```

## Reproducible Demo

```js
<ViroVideo
  source={require('../assets/ar/forest.mp4')}
  width={0.175}
  height={0.2}
  loop={true}
  muted={true}
/>
```

<img src="https://user-images.githubusercontent.com/7217420/119846936-dd669d80-bf0a-11eb-8876-91c2028e60d7.jpg" width="300" />

**Comment by ktemby** [comment]
We addressed this in testing on discord. I was able to get this working by rebuilding viro using the VRTVideo file copied directly from viromedia. https://discord.com/channels/774471080713781259/774474909731782666/829108754070503474

I think the solution for this would be a pull request with the original VRTVideo file.

**Comment by JungHsuan** [comment]
Same here. 
I found a workaround. 
I create a video material by  ``ViroMaterialVideo``  and ``ViroMaterials.createMaterials()`` then assign this material to a ``ViroBox``:

Initialize material and free this material in ``useEffect``
```
 useEffect(() => {
      ViroMaterials.createMaterials({
        video_material: {
          lightingModel: 'Lambert',
          diffuseTexture: { uri: YOUR_VIDEO_URL },
        },
      });
    }
    return () => {
      ViroMaterials.deleteMaterials(['video_material']);
    };
  }, []);
```
In you scene:
```
 <ViroARScene>
      <>
          <ViroMaterialVideo
            material={'video_material'}
            paused={false}
            loop={true}
          />
          <ViroBox
            position={[0, 0, 0]}
            height={height}
            width={width}
            length={length}
            materials={['video_material']}
          />
     </>
</ViroARScene>
```

**Comment by doranteseduardo** [comment]
It's fixed
