### ISSUE TITLE
Works with EAS build ?

### ISSUE THREAD

**Issue by LouisSyfer** [ViroCommunity/viro#239]
Hi the viro community.

I would like to know please if the package is compatible with eas? I tried to do a development build but I always get the same error: "package com.viromedia.bridge does not exist"
I have attached a very explicit screenshot.
All my packages are up to date. The react native version I am using is: 0.72.6

thank you for your explanations
![build failed with viro integration](https://github.com/ViroCommunity/viro/assets/24697671/2a35a965-05f5-4b0c-a91d-0985853b31a1)

**Comment by psanchezUndanet** [comment]
Hi @LouisSyfer 

I'm using this package with react native version 0.71.14 (expo sdk 48) without a issue. To make it work, I followed this:
https://github.com/ViroCommunity/viro/issues/218#issuecomment-1632408994

- Adding `jcenter()` to the repository list in the `android/build.gradle`. 
- Add to the `android/app/build.gradle`  the following:
```
    implementation project(':gvr_common')
    implementation project(':arcore_client')
    implementation project(path: ':react_viro')
    implementation project(path: ':viro_renderer')
    implementation 'com.google.android.exoplayer:exoplayer:2.17.1'
    implementation 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7'
```

In my project I only use the AR component, so I only added `packages.add(new ReactViroPackage(ReactViroPackage.ViroPlatform.valueOf("AR")));` to the MainApplication (i didn't add the `"GVR"` and `"OVR_MOBILE"` as I didn't need them.

I hope this helps. Please let me know if it work (or didn't), to know what to expect when I upgrade to Expo sdk 49, as it will update the react native version.

**Comment by LouisSyfer** [comment]
Hi @psanchezUndanet 

Thanks for your reply. 

Ok I will have a look later. Otherwise I think I may have another solution.

**Comment by Haseebshah936** [comment]
@LouisSyfer can you tell me that if it worked and can you mention the other solution as well thanks

**Comment by LouisSyfer** [comment]
@Haseebshah936 I didn't have the time to try ! But I will let you know if I do it ASAP

**Comment by Haseebshah936** [comment]
@LouisSyfer thanks bud.

**Comment by LouisSyfer** [comment]
@Haseebshah936 I tried the solution above. You can build a dev app. But it's not possible to use Viro. I get another error and I don't have a workaround. Please check the screenshot.
![react-viro-error](https://github.com/NativeVision/viro/assets/24697671/660f2d89-fbf5-4187-9380-29f801ca32da)
