### ISSUE TITLE
Android app crashes when using stack navigator inside the stack 

### ISSUE THREAD

**Issue by Roopal-dev** [ViroCommunity/viro#25]
I am getting crash when using stack navigator inside the tab navigator.Happens when going back to previous screen.
Any help would be appreciated.These are the details of the versions Im using:
"@react-navigation/native": "^5.9.4",
"@react-navigation/material-top-tabs": "^5.3.15",
"@react-navigation/stack": "^5.14.5",
"react-native": "0.64.2",
"@viro-community/react-viro": "git+https://github.com/virocommunity/viro.git",

**Comment by Sandeep155Vibhuti** [comment]
on which Platform android or IOS you have Face this Issue ?

**Comment by Roopal-dev** [comment]
I had mentioned "android app" than it must be Android platform @Sandeep155Vibhuti

**Comment by Sandeep155Vibhuti** [comment]
> Follow this may be it can help you : ->
> [viromedia/viro#620](https://github.com/viromedia/viro/issues/620)

@Roopal-dev you can use detachInactiveScreens={false} Property inside <Stack.Navigator> Like below

<NavigationContainer>
      <Stack.Navigator
        screenOptions={{ headerShown: true }}
        initialRouteName={'stack'}
        detachInactiveScreens={false}
      >
        <Stack.Screen
          name="stack"
          component={NavigationScreen}
        />
</Stack.Navigator>
    </NavigationContainer>

**Comment by ViktorVojtek** [comment]
This should help: https://github.com/ViroCommunity/viro/issues/138#issuecomment-1336503711
