### ISSUE TITLE
If Viro support Huawei AR Engine?

### ISSUE THREAD

**Issue by HerbertHe** [ViroCommunity/viro#28]
The devices of Huawei don't support Google ARCore anymore. When I try to run the demos of Viro at Huawei device, it can't work well. And Huawei provided their own AR Engine for developing AR Apps under HMS SDK, so I want to know if support Huawei AR Engine or if have a plan, thanks.

**Comment by bilewinters** [comment]
No plans at this time, but PRs are always welcome.

As this is a feature request rather than an issue, I'm going to be closing it.
