### ISSUE TITLE
Geolocation implementation.

### ISSUE THREAD

**Issue by danyhiol** [ViroCommunity/viro#32]
How can I place an object in a Geocoordinates system using viro?
The idea is to implement a Pokemon go game-like application, where the user can go to specific places and find a specific object. The issue here is how to do this using viro. 
Basically, I want to convert longitude and latitude into x,y,z coordinates in Viro.
I am aware of [this](https://github.com/viromedia/viro/issues/605) and also [this](https://github.com/viromedia/viro/issues/131). Both are not working. I might be doing something wrong, but it is always showing the object just before my phone. 

Phone OS: Android
Dev OS: MacOS

**Comment by mariansam** [comment]
Hi, check out the https://github.com/ViroCommunity/geoar repo. Also join our [Discord server](https://discord.gg/YfxDBGTxvG), where we have a special #geo-ar channel just about GeoAR. In the future it would be cool to have GeoAR for Viro as a library, so app developers don't have to implement this on their own.

As for the links you sent: the `HelloWorldSceneAR.js.zip` file in [this comment](https://github.com/viromedia/viro/issues/131#issuecomment-377651456) was a good resource for me.

**Comment by danyhiol** [comment]
Fantastic. 
Thanks a lot, that helped me a lot.

**Comment by ansarikhurshid786** [comment]
Android: 
https://developers.google.com/ar/develop/geospatial

iOS: 
https://developer.apple.com/documentation/arkit/argeoanchor

I saw both support geolocation base AR scene.

**Comment by ansarikhurshid786** [comment]
@mariansam doing great. i saw you are playing major role in geoar repository.
