### ISSUE TITLE
Including ViroCore in React Viro

### ISSUE THREAD

**Issue by redlac** [ViroCommunity/viro#40]
Hi, I have built the ```virocore-*.aar``` from the [https://github.com/ViroCommunity/virocore](https://github.com/ViroCommunity/virocore) project, and I would like to include that file in this project, in order to use ViroCore changes in the React app. 

Is this possible?

**Comment by doranteseduardo** [comment]
Building ViroCore for ViroReact requires to run "./gradlew :viroreact:assembleRelease" from de ViroCore android folder and having the Viro repo in the same path as ViroCore.

Then you have to go to the Viro repo and run the bash file in the root.

**Comment by redlac** [comment]
Thanks, I thought my changes weren't being built, but they were!
All good now.
