### ISSUE TITLE
Case use: Looking some info

### ISSUE THREAD

**Issue by CarSanoja** [ViroCommunity/viro#55]
Hello team!

I am looking for information and I would like to know if you can help me. I am interested in knowing if the following is possible:

I want to use the library to show information ONLY when a certain object appears in the scene, for example, a computer, then its specifications will appear in scene. Is it possible to achieve this from the library itself?

If not, then I would have to have some object classifier task that conditions the appearance of information on the screen, correct?

I hope you can help me and any idea is welcome,

Greetings!

**Comment by doranteseduardo** [comment]
Hello!
Unfortunately the current Viro version doesn't support ML.

If that's the only functionality you need (recognition and data display) you could give the arcore_android_sdk repo a look, there is a sample (easy to port to RN) with an approach like the one you describe.

Best regards,
Ed
