### ISSUE TITLE
App crashes on IOS

### ISSUE THREAD

**Issue by vlkpa** [ViroCommunity/viro#61]
Hi, any idea why app crashes on IOS, even on example from app store? React Viro is working on Android. Maybe because of [issue](https://github.com/viromedia/viro/issues/836) or [issue](https://github.com/viromedia/viro/issues/852)? How to solve this?

**Comment by cloud-github** [comment]
Yes, same happened on my side too. It must be issue of iOS version. In iOS 14, it worked fine but in iOS 15 it crashes. You can run the starter demo app and run on IOS. It should work on both version.

**Comment by saeedtkh** [comment]
any news or update on this issue?

**Comment by NS-BOBBY-C** [comment]
Can you provide more information about the crash? What version of React Native, Viro, iOS, etc. were you using to get the crash?

Have you tried the latest release from NPM? (2.22.0)

**Comment by vlkpa** [comment]
It was fixed in latest release - 2.22.0
